@startuml Parcial 2

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-2/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Analytics/AzureEventHub.puml
!includeurl AzurePuml/InternetOfThings/AzureIoTHub.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml
!includeurl AzurePuml/Integration/AzureServiceBusQueue.puml

left to right direction

agent "Raspberry Pi" as devices #fff

AzureIoTHub(iotHub, "IoT Hub", "Standard")
AzureCosmosDb(outputCosmosDb, "Output Database", "1,000 RUs")
AzureServiceBusQueue(serviceBusQueue, "Queue Kardashian")

devices --> iotHub
iotHub --> outputCosmosDb
outputCosmoDb --> serviceBusQueue

@enduml